package com.myspace.sample_wb_pro;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Employee implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Employee() {
    }




}